GITHUB_TOKEN = "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"
COSMOS_URI = "https://krishivanx-db.documents.azure.com:443/"
COSMOS_KEY = "42kAYHgAIhc6Kq0Ap4C8A1nMCGLDvlr71strtuMpDI0QmEgWHpqI3TuWtXcYg6rBk6afQRjqUblPACDbUaIbmw=="
